import type { Collection, Memory } from "./types";

export const memories: Memory[] = [
  {
    id: "m1",
    type: "screenshot",
    title: "Sony A7 IV spec sheet",
    content:
      "Full-frame 33MP BSI CMOS sensor. 4K 60p 10-bit 4:2:2 video. 759-point autofocus. $2,499 body only. Considering as an upgrade from my Sony A6400.",
    createdAt: "2026-03-18T14:22:00Z",
    source: "screenshot",
    tags: ["camera", "gear", "photography"],
    favorite: true,
    collection: "Camera research",
  },
  {
    id: "m2",
    type: "link",
    title: "Fujifilm X-T5 review — IGN",
    content:
      "40MP APS-C X-Trans sensor, compact body, film simulation dials. Reviewers praise stills quality. $1,699 body. Video is limited to 6.2K 29.97p. Not great for hybrid use.",
    createdAt: "2026-02-11T09:45:00Z",
    source: "https://www.ign.com/articles/fujifilm-xt5-review",
    domain: "ign.com",
    tags: ["camera", "gear", "photography"],
    favorite: false,
    collection: "Camera research",
    highlight: "Stills quality praised; video is a weakness.",
  },
  {
    id: "m3",
    type: "note",
    title: "Camera decision criteria",
    content:
      "Budget: max $2,800. Requirements: 4K60 or better, strong autofocus, IBIS, refurb deal acceptable. Want: full-frame sensor, a line of good f/2 primes, weather sealing for travel. Shortlist: Sony A7 IV, Nikon Z6 III, Fuji X-T5 (compromise), Panasonic S5 II.",
    createdAt: "2026-01-27T20:15:00Z",
    source: "note",
    tags: ["camera", "gear", "decision"],
    favorite: true,
    collection: "Camera research",
  },
  {
    id: "m4",
    type: "link",
    title: "Nikon Z6 III announcement",
    content:
      "Partially stacked 24.5MP sensor, 120fps EVF, 6K60 and 4K120 RAW recording. $2,499. Strong hybrid credentials. 14MB/s readout speed. Tradeoffs: no full-res 30fps burst when shooting RAW.",
    createdAt: "2026-01-15T18:00:00Z",
    source: "https://photographylife.com/nikon-z6-iii-announced",
    domain: "photographylife.com",
    tags: ["camera", "gear", "photography"],
    favorite: false,
    collection: "Camera research",
  },
  {
    id: "m5",
    type: "screenshot",
    title: "Used A7 IV market check",
    content:
      "eBay sold listings: A7 IV bodies averaging $1,950–$2,100 for excellent condition. ~$400 below new. One listing with 16-35mm kit at $2,850. Warranty sold separately.",
    createdAt: "2026-03-02T11:30:00Z",
    source: "screenshot",
    tags: ["camera", "gear", "shopping"],
    favorite: false,
    collection: "Camera research",
  },
  {
    id: "m6",
    type: "link",
    title: "Summit apartments — The Kestrel",
    content:
      "1BR from $2,150. 2BR from $2,900. New building, 2025. Amenities: rooftop pool, co-working lounge, dog park, bike storage, in-unit laundry. Pet friendly. 12 min walk to Caltrain. Move-in special: 1 month free on 12-month lease.",
    createdAt: "2026-04-02T17:20:00Z",
    source: "https://www.thekestrelsummit.com",
    domain: "thekestrelsummit.com",
    tags: ["apartment", "housing", "summit"],
    favorite: true,
    collection: "Apartment search",
    highlight: "1 month free · pet friendly · near Caltrain",
  },
  {
    id: "m7",
    type: "screenshot",
    title: "Yardley Court listing screenshot",
    content:
      "2BR/1BA, 1,040 sq ft, classic pre-war building. Rent: $2,450/mo, includes heat & water. Oven/stove gas. Walk-up, 3rd floor. Broker fee: 1 month. Building manager on site. Hardwood floors, big windows, quiet street.",
    createdAt: "2026-03-25T22:10:00Z",
    source: "screenshot",
    tags: ["apartment", "housing", "summit"],
    favorite: false,
    collection: "Apartment search",
  },
  {
    id: "m8",
    type: "note",
    title: "Apartment hunt — what I'm optimizing for",
    content:
      "Priorities: 1) Commute to office ≤ 30 min. 2) Rent ≤ $2,600. 3) In-unit or building laundry. 4) Pet friendly (Mango). Nice-to-have: balcony or big windows, gym, quiet bedrooms, near a grocery store. Open floor plan for WFH setup. Tour blockers: north-facing windows, no AC, elevator-only buildings.",
    createdAt: "2026-02-28T20:40:00Z",
    source: "note",
    tags: ["apartment", "housing", "decision"],
    favorite: true,
    collection: "Apartment search",
  },
  {
    id: "m9",
    type: "link",
    title: "Summit Station lofts",
    content:
      "Converted warehouse lofts. 1BR from $2,600, 2BR from $3,400. 14-ft ceilings, exposed brick, concrete floors. Two blocks from the train. Tiered pricing by floor. Waitlist currently 3–6 months for 1BR.",
    createdAt: "2026-04-05T14:15:00Z",
    source: "https://summitstationlofts.com",
    domain: "summitstationlofts.com",
    tags: ["apartment", "housing"],
    favorite: false,
    collection: "Apartment search",
  },
  {
    id: "m10",
    type: "discussion",
    title: "SMS thread — mom apartment tips",
    content:
      "Mom: 'Ask about what's included. Water, gas, trash all add up here.' 'Go to a building coffee hour if they have one — best way to meet neighbors.' 'Take photos of every unit before you sign.' Solid reminders.",
    createdAt: "2026-03-30T19:05:00Z",
    source: "iMessage",
    tags: ["apartment", "family", "advice"],
    favorite: false,
    collection: "Apartment search",
  },
  {
    id: "m11",
    type: "note",
    title: "Japan trip — draft itinerary",
    content:
      "14 days, Oct 8–22. Tokyo (3 days: Shinjuku, Shibuya, Senso-ji, teamLab) → Hakone ryokan (2 days, Mount Fuji view, onsen) → Kyoto (4 days: Fushimi Inari, Arashiyama, Kinkaku-ji, Nishiki Market) → Osaka (2 days: Dotonbori, Osaka Castle, USJ?) → Nara day trip → back to Tokyo for 2 days (shopping: Marunouchi, Ginza). Buffer day in Tokyo before flight.",
    createdAt: "2026-01-19T16:00:00Z",
    source: "note",
    tags: ["japan", "travel", "plans"],
    favorite: true,
    collection: "Japan trip",
  },
  {
    id: "m12",
    type: "link",
    title: "Hakone ryokan — Gora Kadan",
    content:
      "Traditional ryokan with private onsen in-room. Half-board kaiseki dinner included. Mountain views, gardens. ~$480/night for two. 90 min from Tokyo via Odakyu Romancecar. Seasonal reservation windows open 6 months ahead.",
    createdAt: "2026-02-09T12:30:00Z",
    source: "https://www.gorakadan.com/en/",
    domain: "gorakadan.com",
    tags: ["japan", "travel", "hotel"],
    favorite: true,
    collection: "Japan trip",
    highlight: "Private in-room onsen · kaiseki included",
  },
  {
    id: "m13",
    type: "screenshot",
    title: "JR East rail pass calculation",
    content:
      "14-day nationwide pass: ¥72,900 (~$485). Tokyo→Kyoto Shinkansen round trip alone: ¥27,320. Adding Kyoto→Osaka, Osaka→Nara, and the Hakone detour pushes the math close — pass saves ~¥9,000 total. Worth it if I add Kiso Valley stop. Otherwise regional West pass cheaper.",
    createdAt: "2026-02-20T13:45:00Z",
    source: "screenshot",
    tags: ["japan", "travel", "transit"],
    favorite: false,
    collection: "Japan trip",
  },
  {
    id: "m14",
    type: "link",
    title: "Kyoto day trip — Fushimi Inari secrets",
    content:
      "Go before 7am or after 6pm to avoid crowds. Sumiyoshi-taisha nearby for a quieter shrine. The summit loop is ~4km/2hrs and most people turn back early. To-r gates lit at dusk are gorgeous. Post on SENBON TORII.",
    createdAt: "2026-03-07T08:20:00Z",
    source: "https://www.insidekyoto.com/fushimi-inari",
    domain: "insidekyoto.com",
    tags: ["japan", "travel", "kyoto"],
    favorite: false,
    collection: "Japan trip",
  },
  {
    id: "m15",
    type: "screenshot",
    title: "Pixel 9 Pro spec comparison (new phone?)",
    content:
      "Tensor G4, 6.3\" Actua display, 48MP main + 48MP ultrawide + 48MP telephoto (5x). Gemini Nano built-in. $999 base. vs. iPhone 16 Pro: A18 Pro faster, better battery, but Pixel wins on camera and Google AI features. Since I want the tamron for photos, this matters.",
    createdAt: "2026-04-08T15:40:00Z",
    source: "screenshot",
    tags: ["phone", "tech", "shopping"],
    favorite: false,
    collection: "Tech stack",
  },
  {
    id: "m16",
    type: "document",
    title: "Résumé v4 — Product Designer",
    content:
      "Updated: shifted 'visual design' bullets toward systems thinking and AI workflows. Highlight: shipped a design system across 4 products at Nimbus. Metrics: reduced onboarding churn 18%, NPS +11 after revamp. Added leadership: mentored 2 juniors. Trimmed to 1 page.",
    createdAt: "2026-03-14T10:00:00Z",
    source: "Google Docs",
    tags: ["career", "resume", "job search"],
    favorite: true,
    collection: "Career",
  },
  {
    id: "m17",
    type: "note",
    title: "Weekly review — March 16",
    content:
      "Good: shipped settings redesign, got positive feedback from PM. Picture: rental search progressing, 2 tours this week. Japan: locked Tokyo dates, need to book ryokan. Camera: down to 3 candidates — test one in store this weekend. Next week: portfolio case study for job hunt, 30-min runs Tue/Thu/Sat.",
    createdAt: "2026-03-16T18:30:00Z",
    source: "note",
    tags: ["review", "weekly", "productivity"],
    favorite: false,
    collection: "Journal",
  },
  {
    id: "m18",
    type: "link",
    title: "Homebrew espresso machine guide",
    content:
      "Ranking: Breville Bambino Plus ($499) best value under $600. Rancilio Silvia Pro X ($2,080) for real prosumer. Profitec Go ($1,250+) compact upgrade. Threat: honestly a Bambino + good grinder (Niche Zero $800) beats everything under $1,500. Milk steaming only matters if I drink lattes — I mostly do.",
    createdAt: "2026-02-25T16:10:00Z",
    source: "https://www.homegrounds.co/best-espresso-machine/",
    domain: "homegrounds.co",
    tags: ["coffee", "home", "shopping"],
    favorite: false,
    collection: "Home ideas",
  },
  {
    id: "m19",
    type: "note",
    title: "Gift ideas for Jane's birthday",
    content:
      "Jane likes: watercolor painting, hiking trails in the redwoods, that North Face fleece she keeps wearing, sourdough baking (her starter 'Steven' is alive and healthy), photography classes. Budget: $150. Top idea: a weekend watercolor workshop at the community center + new brush set. Backup: trail shoes gift card.",
    createdAt: "2026-03-22T21:00:00Z",
    source: "note",
    tags: ["gift", "friends", "birthday"],
    favorite: false,
    collection: "Ideas",
  },
  {
    id: "m20",
    type: "screenshot",
    title: "Recipe — sourdough discard crackers",
    content:
      "Roasted garlic rosemary sourdough discard crackers: 1 cup starter discard, 3 tbsp olive oil, 3 tbsp butter, ½ tsp garlic powder, ½ tsp rosemary, pinch flaky salt. Roll thin, score, bake at 350°F 18-22 min. From: 'The Sourdough School' newsletter. Unanimous crowd-pleaser.",
    createdAt: "2026-03-29T15:25:00Z",
    source: "screenshot",
    tags: ["recipe", "baking", "food"],
    favorite: false,
    collection: "Kitchen",
  },
  {
    id: "m21",
    type: "link",
    title: "Urban hiking — Mount Tam trail list",
    content:
      "Matt Davis → Steep Ravine → Dipsea loop: 9.3 mi, ~2,400ft elevation, the classic. Bootjack to Muir Woods for giants. Pantoll to Stinson Beach for ocean views. All require parking reservation on weekends (April–Sept). Best light: early AM.",
    createdAt: "2026-04-01T07:30:00Z",
    source: "https://www.marinmunicipalwater.com",
    domain: "marinmunicipalwater.com",
    tags: ["hiking", "outdoors", "bay area"],
    favorite: true,
    collection: "Hiking",
  },
  {
    id: "m22",
    type: "screenshot",
    title: "Email — Mango vet appointment",
    content:
      "From: VCA Animal Hospital. Subject: Mango's annual checkup confirmed. Date: April 24, 10:30am. Includes: vaccines (DAPP + rabies), fecal, standard exam. Bring: recent donut chew evidence if heartworm suspected. Grooming reminder before beach season.",
    createdAt: "2026-04-06T09:15:00Z",
    source: "Email",
    tags: ["mango", "pets", "appointment"],
    favorite: false,
    collection: "Mango",
  },
  {
    id: "m23",
    type: "document",
    title: "Lease agreement draft — The Kestrel",
    content:
      "12-month lease starting June 1. 1BR unit 4C. First + last due at signing. Includes storage cage and one parking spot ($150/mo for second). Pet fee: $500 one-time + $25/mo. Tenant pays electricity; gas/water/trash included. Break clause after 6 months: 2-months notice + 1-month fee.",
    createdAt: "2026-04-10T16:45:00Z",
    source: "DocuSign",
    tags: ["apartment", "housing", "contract"],
    favorite: true,
    collection: "Apartment search",
  },
  {
    id: "m24",
    type: "link",
    title: "Renting in Summit — neighborhood guide",
    content:
      "Summit hits 'best commuter town' lists again. Rent up 6% YoY but below Bayside. Best coffee: Cool Beans (Summit Ave). Best park: Pinecrest. Watch out: the 'Gates' district has train noise. Dog parks on the north side. Grocery: Summit Market has good produce prices.",
    createdAt: "2026-03-12T20:00:00Z",
    source: "https://www.summitlivingguide.com",
    domain: "summitlivingguide.com",
    tags: ["apartment", "housing", "summit"],
    favorite: false,
    collection: "Apartment search",
  },
  {
    id: "m25",
    type: "note",
    title: "Startup idea — contextual note app",
    content:
      "Problem: personal notes are silos, disconnected from physical spaces and people. Concept: notes auto-attach to location/people/context, retrievable by natural language. Positioning: 'memory, not notebook.' Could combine with Revo OS-style memory layer. Feasibility: MVP with vector similarity + LLM summarization, test with 50 users.",
    createdAt: "2026-01-10T22:30:00Z",
    source: "note",
    tags: ["idea", "startup", "product"],
    favorite: true,
    collection: "Ideas",
  },
  {
    id: "m26",
    type: "screenshot",
    title: "Flight deal — Tokyo nonstop $680",
    content:
      "SFO→NRT nonstop, Japan Airlines, Oct 8. Return Oct 22 economy. $680 all-in. Bag: first checked bag free (on JAL for this fare bucket — verify). Seat selection $0. Scotts Cheap Flights alert. Booking window is open — grab within 48h.",
    createdAt: "2026-04-04T11:00:00Z",
    source: "screenshot",
    tags: ["japan", "travel", "flights"],
    favorite: true,
    collection: "Japan trip",
    highlight: "Nonstop · $680 all-in · book within 48h",
  },
  {
    id: "m27",
    type: "discussion",
    title: "Group chat — Japan partners",
    content:
      "Tom & Priya confirmed for Kyoto leg (Oct 11–14). Alex might join Tokyo first 3 days. Everyone chill with the ryokan night being spendy. Tentative: split a day in Osaka doing a food crawl, skip USJ. Will finalize split once base itinerary is locked.",
    createdAt: "2026-02-14T21:20:00Z",
    source: "WhatsApp",
    tags: ["japan", "travel", "friends"],
    favorite: false,
    collection: "Japan trip",
  },
  {
    id: "m28",
    type: "screenshot",
    title: "Figma screenshot — settings redesign v2",
    content:
      "New settings layout: left nav with 'Account', 'Privacy', 'Integrations', 'Billing', 'Keyboard shortcuts'. Main zone holds cards with description-first copy. Toasts instead of inline saves. Empty states with illustration + next action CTA. Reviewer feedback: reduce nesting depth, move 'danger zone' to bottom.",
    createdAt: "2026-03-13T14:00:00Z",
    source: "Figma",
    tags: ["work", "design", "product"],
    favorite: false,
    collection: "Career",
  },
  {
    id: "m29",
    type: "note",
    title: "Streaming — what to watch next",
    content:
      "Backlog: 'Severance S2' (Apple TV), 'The Bear S4' (Hulu), 'Dune: Prophecy' (Max), 'Slow Horses S5' (Apple). Rebooked: 'Severance' first, tonight with dinner. Also want the new Studio Ghibli 4K set, on sale for the moss green slipcase at B&N.",
    createdAt: "2026-04-09T19:50:00Z",
    source: "note",
    tags: ["entertainment", "watchlist", "tv"],
    favorite: false,
    collection: "Entertainment",
  },
  {
    id: "m30",
    type: "link",
    title: "Best low-light tamron lens for Sony E",
    content:
      "Tamron 24-70mm f/2.8 G2 ($1,199) best all-rounder. Tamron 35mm f/1.4 SP ($599) for portraits/low light. Tamron 17-28mm f/2.8 ($799) for travel/landscape. All have weather sealed options — pairing with A7 IV's IBIS gives exceptional handholding at night.",
    createdAt: "2026-04-07T10:30:00Z",
    source: "https://www.lensrentals.com/blog/tamron-sony-e",
    domain: "lensrentals.com",
    tags: ["camera", "gear", "lens"],
    favorite: true,
    collection: "Camera research",
  },
  {
    id: "m31",
    type: "note",
    title: "Reading list — April",
    content:
      "In progress: 'The Creative Act' by Rick Rubin — mindset around creativity. 'Four Thousand Weeks' — time management re-frame. Next: 'The Man in the High Castle'. Audiobook: 'Project Hail Mary' on deck for commute. Highlight: Rubin's 'make space, not time' quote on repeat.",
    createdAt: "2026-04-02T08:15:00Z",
    source: "note",
    tags: ["reading", "books", "wellbeing"],
    favorite: false,
    collection: "Reading",
  },
  {
    id: "m32",
    type: "screenshot",
    title: "Gym plan — PPL split for the quarter",
    content:
      "Push/Pull/Legs 4x/week: Monday Push, Tuesday Pull, Thursday Legs, Saturday Push + core. 8-12 rep range for hypertrophy; 0-2 RIR. Progression: add 2.5lb weekly on compounds until pause, then deload. Track in Strong app. Rogue plates & knockoff adjustable dumbbells from FB marketplace check out fine.",
    createdAt: "2026-01-06T06:30:00Z",
    source: "screenshot",
    tags: ["fitness", "health", "routine"],
    favorite: false,
    collection: "Health",
  },
  {
    id: "m33",
    type: "email",
    title: "Emails — Switzerland conference",
    content:
      "CFP for UX Design Summit 2026 extended to May 15. Submission idea: 'Designing for memory systems' — reuse Revo OS learnings. Budget request to manager for Zurich trip (he's into it, 'frame as R&D'). June 2–4. Talks 45 min incl. Q&A. Travel stipend available.",
    createdAt: "2026-04-08T10:12:00Z",
    source: "Email",
    tags: ["career", "conference", "speaking"],
    favorite: false,
    collection: "Career",
  },
  {
    id: "m34",
    type: "image",
    title: "Photo — Mango in the park",
    content:
      "Golden retriever puppy, 8 months. Took him to Pinecrest Park, first time meeting the new German shepherd pup ('Duke'). Chased a leaf for 10 minutes straight. Printed a copy for the fridge at home. Mango is the good boy, 10/10.",
    createdAt: "2026-04-11T17:45:00Z",
    source: "Photos",
    tags: ["mango", "dog", "photo"],
    favorite: true,
    collection: "Mango",
  },
  {
    id: "m35",
    type: "link",
    title: "Watercolor workshops — community center",
    content:
      "Weekend watercolor workshops at Summit Community Center. 'Beginner Studio' every Saturday 10am-1pm, $35/drop-in, supplies included. Next month: 'Plein air watercolor at Pinecrest' June 8. Perfect gift base for Jane — gift her Saturday session + brush set.",
    createdAt: "2026-04-03T13:40:00Z",
    source: "https://www.summitparks.org/classes",
    domain: "summitparks.org",
    tags: ["gift", "jane", "classes"],
    favorite: false,
    collection: "Ideas",
  },
];

export const collections: Collection[] = [
  {
    id: "c1",
    name: "Camera research",
    emoji: "📸",
    description: "Specs, reviews, and shortlist for the next camera",
    memoryCount: 6,
    color: "from-amber-500/20 to-orange-500/5",
  },
  {
    id: "c2",
    name: "Apartment search",
    emoji: "🏠",
    description: "Summit listings, comparisons, and deal-breakers",
    memoryCount: 8,
    color: "from-sky-500/20 to-indigo-500/5",
  },
  {
    id: "c3",
    name: "Japan trip",
    emoji: "🗾",
    description: "Itinerary, flights, ryokan, and trains for October",
    memoryCount: 7,
    color: "from-rose-500/20 to-pink-500/5",
  },
  {
    id: "c4",
    name: "Career",
    emoji: "💼",
    description: "Résumé, projects, and speaking opportunities",
    memoryCount: 4,
    color: "from-violet-500/20 to-purple-500/5",
  },
  {
    id: "c5",
    name: "Ideas",
    emoji: "💡",
    description: "Concepts, gifts, and sketches worth keeping",
    memoryCount: 3,
    color: "from-emerald-500/20 to-teal-500/5",
  },
  {
    id: "c6",
    name: "Kitchen",
    emoji: "🍳",
    description: "Recipes and gear to try",
    memoryCount: 1,
    color: "from-yellow-500/20 to-lime-500/5",
  },
  {
    id: "c7",
    name: "Mango",
    emoji: "🐕",
    description: "Everything about the golden retriever",
    memoryCount: 2,
    color: "from-lime-500/20 to-green-500/5",
  },
  {
    id: "c8",
    name: "Hiking",
    emoji: "🥾",
    description: "Bay Area trails and day hikes",
    memoryCount: 1,
    color: "from-green-500/20 to-emerald-500/5",
  },
  {
    id: "c9",
    name: "Health",
    emoji: "💪",
    description: "Fitness, habits, and wellbeing",
    memoryCount: 1,
    color: "from-red-500/20 to-rose-500/5",
  },
];

export const exampleQueries = [
  "What have I been researching lately?",
  "What cameras have I been considering?",
  "What apartments did I save?",
  "When is Mango's vet appointment?",
];

export const formattingRules = {
  date: new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }),
};

export const memoryTypeMeta: Record<Memory["type"], { label: string; icon: string }> = {
  screenshot: { label: "Screenshot", icon: "Monitor" },
  note: { label: "Note", icon: "StickyNote" },
  document: { label: "Document", icon: "FileText" },
  link: { label: "Link", icon: "LinkIcon" },
  image: { label: "Image", icon: "ImageIcon" },
  discussion: { label: "Conversation", icon: "MessageSquare" },
  email: { label: "Email", icon: "Mail" },
  archive: { label: "Archive", icon: "Archive" },
};